// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1p4mCuKU9gQ2mYxSKLnqx7f1_g_QxTc',
    appId: '1:590531687616:ios:bead7be75272b87172e925',
    messagingSenderId: '590531687616',
    projectId: 'coffeeapp-98838',
    storageBucket: 'coffeeapp-98838.firebasestorage.app',
    iosBundleId: 'com.jdtech.coffeapp.coffe',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxHjVa5Ut6N7QKlApdAn3nT0EukZXKdI',
    appId: '1:590531687616:web:3b03c11feb04684d72e925',
    messagingSenderId: '590531687616',
    projectId: 'coffeeapp-98838',
    authDomain: 'coffeeapp-98838.firebaseapp.com',
    storageBucket: 'coffeeapp-98838.firebasestorage.app',
    measurementId: 'G-R9ERXJF1XZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW1p4mCuKU9gQ2mYxSKLnqx7f1_g_QxTc',
    appId: '1:590531687616:ios:3074ac6ac624af9e72e925',
    messagingSenderId: '590531687616',
    projectId: 'coffeeapp-98838',
    storageBucket: 'coffeeapp-98838.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3dgm4yhFGvWNScbYCpnyBWDQzEf26LM',
    appId: '1:590531687616:android:624dad233cd5622b72e925',
    messagingSenderId: '590531687616',
    projectId: 'coffeeapp-98838',
    storageBucket: 'coffeeapp-98838.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxHjVa5Ut6N7QKlApdAn3nT0EukZXKdI',
    appId: '1:590531687616:web:8aa1ea9db6608be372e925',
    messagingSenderId: '590531687616',
    projectId: 'coffeeapp-98838',
    authDomain: 'coffeeapp-98838.firebaseapp.com',
    storageBucket: 'coffeeapp-98838.firebasestorage.app',
    measurementId: 'G-2MECF625DY',
  );

}